language: ruby
cache:
  - bundler
  - pip

sudo: required
dist: trusty # or installing google-chrome-stable will fail

before_install:
  - gem install bundler
  - sudo apt-get -qq update
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - sudo tar -C /usr/bin -zxf geckodriver-v0.11.1-linux64.tar.gz
  - sudo dpkg -i google-chrome-stable_current_amd64.deb

bundler_args: --without debugger

script:
  - bundle exec rake test
  - bundle exec rake spec

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.3.1
matrix:
  allow_failures:
    - rvm: ruby-head
