language: ruby
cache:
  - bundler

sudo: required
dist: trusty # or installing google-chrome-stable will fail

before_install:
  - gem install bundler
  - sudo apt-get -qq update
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - sudo tar -C /usr/bin -zxf geckodriver-v0.11.1-linux64.tar.gz
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - bundle install --path vendor
  - wget https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
  - ls -l /home/travis/virtualenv
  - sudo unzip chromedriver_linux64.zip -d /usr/bin
  - export CHROME_BIN=chromium-browser

bundler_args: --without debugger

script:
  - bundle exec rake test
  - bundle exec rake spec

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.3.1
matrix:
  allow_failures:
    - rvm: ruby-head
