language: ruby
before_install:
  - gem install bundler
  - sudo apt-get install nodejs nodeenv
  - source env/bin/activate

bundler_args: --without debugger

script:
  - bundle exec rake test

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.3.1
matrix:
  allow_failures:
    - rvm: ruby-head
