#!/usr/bin/env ruby
# Start steinwies for spec tests or debugging purpose
# Order of include is very important, as patch the configuration information
# for Mail, URL, etc.
$: << File.expand_path('../src', File.dirname(__FILE__))
$0 = 'SteinwiesTest'
puts  File.expand_path('../src', File.dirname(__FILE__))
require 'drb/drb'
require 'util/config'
$: << File.expand_path('..', File.dirname(__FILE__))
require 'spec/tst_util'
require 'steinwies'
Steinwies.config.server_name=TEST_SRV_URI.to_s
require 'util/app'

SBSM.info msg = "Starting #{Steinwies.config.server_uri}"
DRb.start_service(Steinwies.config.server_uri, Steinwies::AppWebrick.new)
DRb.thread.join
